### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by stardiviner** [sourcegraph/tern-def-origin#2]
I want to use [Sourcegraph](https://sourcegraph.com) for tern-def-origin code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/sourcegraph/tern-def-origin. (It should only take 30 seconds.)

Thank you!

**Comment by beyang** [comment]
I enabled it, but unfortunately, it looks like the build was not successful (no links were found). Our JavaScript support is currently in alpha, but we are working on improving it soon. Thanks for trying out Sourcegraph and let us know if you have any additional feedback!
